const CHANGE_FILTERS = 'CHANGE_FILTERS'

const GET_SEARCH_ID = 'GET_SEARCH_ID'
const GET_SEARCH_ID_SUCCESS = 'GET_SEARCH_ID_SUCCESS'
const GET_SEARCH_ID_FAILED = 'GET_SEARCH_ID_FAILED'

export default {
  CHANGE_FILTERS,
  GET_SEARCH_ID,
  GET_SEARCH_ID_SUCCESS,
  GET_SEARCH_ID_FAILED,
}
