export const CHANGE_FILTERS = 'CHANGE_FILTERS'

export const GET_SEARCH_ID = 'GET_SEARCH_ID'
export const GET_SEARCH_ID_SUCCESS = 'GET_SEARCH_ID_SUCCESS'
export const GET_SEARCH_ID_FAILED = 'GET_SEARCH_ID_FAILED'

export const GET_TICKETS = 'GET_TICKETS'
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS'
export const GET_TICKETS_FAILED = 'GET_TICKETS_FAILED'
